class Book:
    
    def __init__(self,title,author,isbn :int):  
        self.title = title
        self.author =author
        self.isbn = isbn
        self.available = True #initial state should be true

    def display_info(self):  #shows all the information about book
        return f"-----------------\ntitle = {self.title}\nauthor = {self.author}\nISBN = {self.isbn}\nAvailable = {self.available}\n-----------------"
    
    def is_available(self):  #shows if book is available
        if self.available == True:
            return f'{self.title} is available'
        else:
            return f'{self.title} is unavailable'
        
    def mark_issue(self):   #run when book is given to customer
        if self.available == True:
            self.available = False
        else:
            print(f"{self.title} already issued")
        
    def mark_return(self):  #run when book is given back
        self.available = True



class Member:
    
    def __init__(self, name , member_id):
        self.name = name
        self.member_id = member_id
        self.borrowed_books = []

    def borrow_book(self ,book):
        if book.available:
            book.mark_issue()
            self.borrowed_books.append(book)
            print(f'{self.name} has borrowed {book.title}')
        else:
            print(f'{book.title} has already been issued')

    def return_book(self,book):
        if book in self.borrowed_books:
            book.mark_return()
            self.borrowed_books.remove(book)
            print(f'{book.title} has been returned by {self.name}')
        else:
            print(f'{self.name} never borrowed {book.title}')

    def view_borrowed_book(self):
        if self.borrowed_books:
            print(f"\n{self.name}'s Borrowed Books:")
            for book in self.borrowed_books:
                print(f"{book.title} by {book.author}")
        else:
            print(f"{self.name} has not borrowed any books.")



class Library:
    def __init__(self):
        self.books = {}
        self.members = {}

    def add_book(self):
        title = input("enter title of book")
        author = input("enter author of book")
        isbn = input("enter isbn of book")


        if isbn in self.books:
            print("book with same isbn already exists in our system")
            return
        
        book_1 = Book(title, author,isbn)
        self.books[isbn]= book_1
        print(f"'{title}' by {author} added to the library.")

    def add_member(self):
        name = input("enter your name")
        member_id = input("enter your member_id")


        if member_id in self.members:
            print("member_id already exists in our system")
            return
        
        member_1 = Member(name,member_id)
        self.members[member_id]= member_1
        print(f"'{name}' is add to our system with member_id {member_id} .")
    
    def find_book(self,isbn_or_title):
        
        if isbn_or_title in self.books:
            book = self.books[isbn_or_title]
            print(f'Book found: {book.title} by {book.author} (isbn {book.isbn})')
            return book 
        
        for book in self.books.values():
            if book.title.lower() == isbn_or_title.lower():
                print(f"Book found: '{book.title}' by {book.author} (ISBN: {book.isbn})")
            return book
        
        print("Book not found.")
        return None
    
    def display_book(self, identifier=None):
        if not self.books:
            print("No books available in the library.")
            return

        if identifier is None:
            print("\n📚 List of Books:")
            for book in self.books.values():
                print(book.display_info())  # Assuming `Book` class has `display_info()`
        
        else:
            if identifier in self.books:
                print("\n📖 Book Found:")
                print(self.books[identifier].display_info())
                return
            
            for book in self.books.values():
                if book.title.lower() == identifier.lower():
                    print("\n📖 Book Found:")
                    print(book.display_info())
                    return
            
            print("❌ Book not found.")




# ALL OF THE TEST WERE GENERATED BY CHATGPT

# 🟢 Create Book instances
book1 = Book("Python Basics", "John Doe", "12345")
book2 = Book("Data Science", "Jane Smith", "67890")
book3 = Book("Machine Learning", "Alice Brown", "11223")

# 🟢 Test Book Class
print("\n📌 Test 1: Display Book Info")
print(book1.display_info())  # Expected: Python Basics details

print("\n📌 Test 2: Check if Book is Available")
print(book1.is_available())  # Expected: 'Python Basics is available'

print("\n📌 Test 3: Issue a Book")
book1.mark_issue()
print(book1.is_available())  # Expected: 'Python Basics is unavailable'

print("\n📌 Test 4: Return a Book")
book1.mark_return()
print(book1.is_available())  # Expected: 'Python Basics is available'

# 🟢 Create Member instance
member1 = Member("Aryan", "101")
member2 = Member("Riya", "102")

# 🟢 Test Member Class
print("\n📌 Test 5: Borrow a Book")
member1.borrow_book(book1)  # Expected: Aryan borrows 'Python Basics'

print("\n📌 Test 6: View Borrowed Books")
member1.view_borrowed_book()  # Expected: Lists 'Python Basics'

print("\n📌 Test 7: Try Borrowing an Issued Book")
member2.borrow_book(book1)  # Expected: 'Python Basics has already been issued'

print("\n📌 Test 8: Return a Book")
member1.return_book(book1)  # Expected: 'Python Basics has been returned by Aryan'

print("\n📌 Test 9: View Borrowed Books After Returning")
member1.view_borrowed_book()  # Expected: No books borrowed

# 🟢 Create Library instance
library = Library()

# 🟢 Test Library Class
print("\n📌 Test 10: Add Books to Library")
library.add_book()  # Expected: User enters book details, and it's added to the library

print("\n📌 Test 11: Add Duplicate Book")
library.add_book()  # Expected: Duplicate ISBN should not be added

print("\n📌 Test 12: Add Members to Library")
library.add_member()  # Expected: User enters details, and member is added

print("\n📌 Test 13: Find Book by ISBN")
library.find_book("12345")  # Expected: Finds and prints 'Python Basics' info

print("\n📌 Test 14: Find Book by Title")
library.find_book("Data Science")  # Expected: Finds and prints 'Data Science' info

print("\n📌 Test 15: Display All Books")
library.display_book()  # Expected: Lists all available books

print("\n📌 Test 16: Display Specific Book")
library.display_book("12345")  # Expected: Shows 'Python Basics' details

print("\n📌 Test 17: Try Finding Non-Existent Book")
library.find_book("Artificial Intelligence")  # Expected: 'Book not found'


        
        
